# Generated by Django 4.2.1 on 2023-06-09 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='fechaMovimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fechaMovimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
