# Generated by Django 4.2.1 on 2023-07-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresoproducto',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.egreso'),
        ),
        migrations.AlterField(
            model_name='egresoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.producto'),
        ),
        migrations.AlterField(
            model_name='ingresoproducto',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.ingreso'),
        ),
        migrations.AlterField(
            model_name='ingresoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.producto'),
        ),
    ]
