# Generated by Django 4.2.1 on 2023-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_run_alter_proveedor_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='fecha',
            new_name='fechaSistema',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha',
            new_name='fechaSistema',
        ),
        migrations.AddField(
            model_name='egreso',
            name='fechaMovimiento',
            field=models.DateTimeField(default='2023-09-06'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fechaMovimiento',
            field=models.DateTimeField(default='2023-09-06'),
        ),
    ]
