# Generated by Django 4.2.1 on 2023-07-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_egreso_cliente_alter_egresoproducto_egreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
    ]
