# Generated by Django 4.2.1 on 2023-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='---', max_length=100, null=True, unique=True),
        ),
    ]
