# Generated by Django 4.2.1 on 2023-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='---', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
